server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vcode
    username: root
    password: ""
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: test
